name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:

  build:

    runs-on: ubuntu-latest

    services:

      postgres:
        image: postgres:17-alpine
        env:
          POSTGRES_USER: masterdetails
          POSTGRES_PASSWORD: ci_password
          POSTGRES_DB: masterdetails
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U masterdetails -d maserdetails"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

      redis:
        image: redis:8.2-alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd="redis-cli ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: maven

      - name: Run tests
        env:
          PGSQL_HOSTNAME: localhost
          PGSQL_USERNAME: masterdetails
          PGSQL_PASSWORD: ci_password
          REDIS_HOSTNAME: localhost
        run: ./mvnw test

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.WRITE_PACKAGES_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push docker image
        id: build-and-push
        uses: docker/build-push-action@v6
#        env:
#          PGSQL_HOSTNAME: host.docker.internal
#          PGSQL_USERNAME: masterdetails
#          PGSQL_PASSWORD: ci_password
#          REDIS_HOSTNAME: host.docker.internal
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
#          build-args: PGSQL_HOSTNAME=host.docker.internal,PGSQL_USERNAME=masterdetails,PGSQL_PASSWORD=ci_password,REDIS_HOSTNAME=host.docker.internal
